name: "Lab meeting reminder"
on:
  workflow_dispatch:
  schedule:
    - cron: "10,40 9,10,14,15 * * 4"

jobs:
  remind-meeting:
    runs-on: ubuntu-latest
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@master

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            pkgload
            httr
            curl@6.1.1

      - name: Remind meeting
        env:
          SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.EPIFORECASTS_WEBHOOK }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          ZOOM_ROOM: ${{ secrets.ZOOM_ROOM }}
        run: |
          pkgload::load_all(".")
          googlesheets4::gs4_deauth()
          this_week_plan <- get_meeting_info(Sys.getenv("GSHEET_ID"))
          msg <- create_announcement_reminder(
            assignee = this_week_plan[["Speaker"]],
            random = this_week_plan[["Random"]],
            chair = this_week_plan[["Chair"]],
            notes = this_week_plan[["Notetaking"]],
            topic = this_week_plan[["Topic"]],
            zoom_link = Sys.getenv("ZOOM_ROOM"),
            room = this_week_plan[["Room"]],
            time = this_week_plan[["Time"]]
          )
          if (!is.null(msg)) {
            req <- httr::POST(
              url = Sys.getenv("SLACK_INCOMING_WEBHOOK_URL"),
              body = list(text = msg, type = "mrkdwn"),
              encode = "json"
            )
            httr::stop_for_status(req)
          }
        shell: Rscript {0}
